# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Github CI

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# - script: |
#    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
#    chmod +x codeql-runner-linux
#   displayName: 'Get latest CodeQL package. Install on Agent.'

# - script: |
#    ./codeql-runner-linux init --languages csharp --repository tvcastilho/codeql-dotnet-demo --github-url https://github.com --github-auth $(github_pat2)
#   displayName: 'Initialize CodeQL Executable and create a CodeQL database'

# - script: |
#    ./codeql-runner-linux analyze --repository tvcastilho/codeql-dotnet-demo --github-url https://github.com --github-auth $(github_pat2) --commit 0d60c02d98442dc2a9ac94f00509536c4970fb52 --ref refs/heads/main
#   displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'

- powershell: |
          # Guide here https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/running-codeql-code-scanning-in-your-ci-system
          $currentBranch = "$(Build.SourceBranch)".Substring("refs/heads".Length + 1)
          # Write-Host "Current branch to push on GitHub is $currentBranch"
          # git push https://$(ghtoken)@github.com/alkampfergit/fantastic-log-library.git "origin/$currentBranch`:$currentBranch" --force
          # Write-Host "downloading Code QL analysis for windows"
          # $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -uri https://github.com/github/codeql-action/releases/latest/download/codeql-runner-win.exe -OutFile $(Build.SourcesDirectory)\src\codeql-runner-win.exe
          Write-Host "Code QL analysis for windows downloaded, now we init it"
          cd $(Build.SourcesDirectory)
          pwd 
          & ./codeql-runner-win.exe init --github-url https://github.com --repository tvcastilho/codeql-dotnet-demo --github-auth $(github_pat2) --languages csharp
         
          cat $(Build.SourcesDirectory)\codeql-runner\codeql-env.sh | Invoke-Expression
          dotnet restore
          dotnet build
          Write-Host "Analyzing with codeql"
          & ./codeql-runner-win.exe analyze --github-url https://github.com --repository alkampfergit/fantastic-log-library --github-auth $(github_pat2) --commit $(Build.SourceVersion) --ref $(Build.SourceBranch)
  displayName: Analyze with code QL
