# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Github CI

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- script: |
   ./codeql-runner-linux init --repository tvcastilho/codeql-dotnet-demo --github-url https://github.com --github-auth $(GITHUB_PAT)
  displayName: 'Initialize CodeQL Executable and create a CodeQL database'

- script: |
   ./codeql-runner-linux analyze --repository tvcastilho/codeql-dotnet-demo --github-url https://github.com --github-auth $GITHUB_PAT --commit a6a9a6a5f4e941b04934997f4e7a75a034a440af --ref refs/heads/main
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'
